- CMakeLists.txt
- include/calculator/MotorShaftPower.h
- tests/Atmosphere.unit.cpp
Fixed header file MotorShaftPower.h
> Header fix

- CMakeLists.txt
- cmake/CompilerFlags.cmake
- third_party/catch/catch.hpp
- third_party/sqlite/sqlite3.h
> Update third party libraries and fix build error

- binding.gyp
Changed the binding.gyp to work with building on linux.
> changed binding.gyp to work with building on linux

- bindings/db.h
- include/calculator/losses/GasFlueGasMaterial.h
- include/calculator/losses/GasLoadChargeMaterial.h
- include/calculator/losses/LiquidLoadChargeMaterial.h
- include/calculator/losses/SolidLiquidFlueGasMaterial.h
- include/calculator/losses/SolidLoadChargeMaterial.h
- src/sqlite/SQLite.cpp
- tests/SQLite.unit.cpp
- tests/js/dbBindingsTest.js
Adds id's to the objects returned from the database selects
> Includes id in objects returned from the database

- bindings/db.cpp
- bindings/db.h
- include/calculator/losses/SolidLiquidFlueGasMaterial.h
- include/sqlite/SQLite.h
- src/sqlite/SQLite.cpp
- tests/SQLite.unit.cpp
- tests/js/dbBindingsTest.js
Add the ability to delete (only user-added / custom) materials from the database, for all existing materials.
> Db add deletions

- bindings/psat.h
This fixes variable names in head tool NAN binding
> fix variable names in NAN binding for head tool calculator

- tests/HeadTool.unit.cpp
- tests/js/psat.js
Adds headtool unit tests for javascript nan bindings, as well as expands the current C++ head tool unit tests
> add head tool javascript unit tests

- bindings/phast.h
- include/calculator/losses/EnergyInputExhaustGasLosses.h
- src/calculator/losses/EnergyInputExhaustGasLosses.cpp
- tests/EnergyInputExhaustGasLosses.unit.cpp
- tests/js/lossesTest.js
adds an exhaustGasLosses calc to energyInputExhaustGasLosses and cleans up the codebase for this file
> Electric non eaf exhaust gas

- binding.gyp
- bindings/db.h
- bindings/psat.h
- bindings/ssmt.h
- bindings/standalone.h
- include/calculator/losses/GasLoadChargeMaterial.h
- include/calculator/motor/EstimateFLA.h
- include/calculator/motor/MotorCurrent.h
- include/calculator/motor/Poles.h
- src/calculator/motor/EstimateFLA.cpp
- src/calculator/motor/MotorCurrent.cpp
- src/calculator/motor/MotorEfficiency.cpp
- src/calculator/motor/MotorEfficiency25.cpp
- src/calculator/motor/OptimalMotorSize.cpp
- src/sqlite/SQLite.cpp
And also make a few minor optimizations with const references. Change one algorithm in OptimalMotorSize to be log(n) instead of linear
> Fix type conversion errors and warnings for all bindings files

- src/calculator/losses/GasLoadChargeMaterial.cpp
- src/calculator/losses/LiquidLoadChargeMaterial.cpp
- src/calculator/losses/SolidLoadChargeMaterial.cpp
Quick modifications to solid, liquid, and gas load charge materials as per issue 722 at https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/722
> Modify solid, liquid and gas load charge material calculations

- .travis.yml
> add travis CI to the project

- .travis.yml
And use different package managers depending on whether the CI machine is macOS or linux
> Build doxygen in CI

- include/calculator/losses/Atmosphere.h
- include/calculator/losses/FixtureLosses.h
- include/calculator/losses/LiquidLoadChargeMaterial.h
- include/calculator/losses/SolidLoadChargeMaterial.h
- include/calculator/losses/WallLosses.h
- src/calculator/losses/Atmosphere.cpp
- src/calculator/losses/FixtureLosses.cpp
- src/calculator/losses/LiquidLoadChargeMaterial.cpp
- src/calculator/losses/SolidLoadChargeMaterial.cpp
- src/calculator/losses/WallLosses.cpp
- tests/LiquidLoadChargeMaterial.unit.cpp
- tests/SolidLoadChargeMaterial.unit.cpp
- tests/WallLosses.unit.cpp
- tests/js/lossesTest.js
The modifies Solid and Liquid load charge material heat calculations, and includes correction factor in the Wall Losses calculations. 
Closes the following issues: 
https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/773
https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/770
> Issue 773, Issue 770 and 776

- include/calculator/furnace/O2Enrichment.h
- src/calculator/furnace/O2Enrichment.cpp
- tests/O2Enrichment.unit.cpp
- tests/js/furnaceTest.js
Adds unit tests and refactors the source code for o2 enrichment to be more streamlined.
> Refactor o2 enrichment

- .travis.yml
- bindings/phast.cpp
- bindings/phast.h
- include/calculator/losses/SolidLiquidFlueGasMaterial.h
- src/calculator/losses/SolidLiquidFlueGasMaterial.cpp
- tests/SolidLiquidFlueGasMaterial.unit.cpp
- tests/js/lossesTest.js
Adds methods for calculation excess air given flue gas O2 and a method for calculating flue gas O2 given excess air and unit tests
> add bindings for new flue gas by mass

- CMakeLists.txt
- binding.gyp
- bindings/standalone.cpp
- bindings/standalone.h
- include/calculator/util/CompressedAir.h
- src/calculator/util/CompressedAir.cpp
- tests/CompressedAir.unit.cpp
- tests/js/standalone.js
connect #161 
connect #163 
Adds implementations and unit tests for Compressed Air Systems, both C++ and NAN methods
> Compressed air

- bindings/standalone.h
- tests/js/standalone.js
connect #190 
Updates airSystemCapacity binding the return an array
> Update airSystemCapacity bindings

- bindings/db.cpp
- bindings/db.h
- tests/js/dbBindingsTest.js
connects #192 
Adds NAN bindings for select all, select by id, insert and delete for motor data
> Add motor bindings

- bindings/fan.cpp
- bindings/fan.h
- include/fans/Fan.h
- include/fans/Planar.h
- src/fans/Planar.cpp
- tests/js/fanTest.js
connects #199 
- Adds getBaseGasDensity binding to grab gas density from the BaseGasDensity class
- Adds getVelocityPressureData binding to grab data from the traverse plane passed in
> Update fan bindings

- bindings/fan.cpp
- bindings/fan.h
- tests/js/fanTest.js
connects #202 
- Adds three methods to replace the one getGasDensity method
> Update getGasDensity bindings

- bindings/db.cpp
- bindings/db.h
- include/calculator/losses/Atmosphere.h
- include/calculator/losses/GasLoadChargeMaterial.h
- include/calculator/losses/LiquidLoadChargeMaterial.h
- include/calculator/losses/LoadChargeMaterial.h
- include/calculator/losses/SolidLiquidFlueGasMaterial.h
- include/calculator/losses/SolidLoadChargeMaterial.h
- include/calculator/losses/WallLosses.h
- include/calculator/util/CompressedAir.h
- include/sqlite/SQLite.h
- package.json
- src/sqlite/SQLite.cpp
- tests/SQLite.unit.cpp
- tests/js/dbBindingsTest.js
connects #225 
connects #223 
connects #226 
- Updates sqlite delete methods to use prepared statements
- Adds sqlite methods for updating rows and NAN bindings for these methods
- Adds both C++ and javascript unit tests for the newly added and modified methods
> Update db methods

- bindings/db.h
- include/sqlite/SQLite.h
- src/sqlite/SQLite.cpp
connects #229 
- Updates the db delete methods to check for attempts to delete default or non-existent materials, returning true or false accordingly.
> Update DB delete methods

- bindings/fan.h
- include/results/Results.h
- src/results/Results.cpp
- tests/Results.unit.cpp
- tests/js/fanTest.js
- Adds user defined fan efficiencies to fsat modified and optimal methods
> User defined fan efficiency

- tests/MotorCurrent.unit.cpp
> Replaced old MotorCurrent unit tests with corrected ones with Kristina's help

- src/results/Results.cpp
connect #246 
Fixed results.cpp
> changed results.cpp

- CMakeLists.txt
- bindings/fan.cpp
- bindings/fan.h
- tests/js/fanTest.js
connects #249 
- Add binding for OptimalFanEfficiency::calculate
- Add js unit test
> add node binding for optimal fan efficiency and a unit test

- bindings/fan.cpp
- bindings/fan.h
- bindings/ssmt.h
- tests/js/fanTest.js
connect #254 
- Add compressibility factor node binding
:us: :fireworks: :+1:
> adds a compressibility factor node binding

- src/ssmt/HeatLoss.cpp
> altered heat loss calculation

- CMakeLists.txt
- include/ssmt/HeatExchanger.h
- include/ssmt/SteamSystemModelerTool.h
- tests/HeatExchanger.unit.cpp
closes #278 
- Adds HeatExchanger calculator
- Adds unit tests for it
- This is a C++ internal use only calculator so no bindings are needed
> SSMT heat exchanger

- bindings/ssmt.h
- tests/js/ssmtTest.js
Minor cleanup before adding conversions for Steam Modeler.
> ssmt.h cleanup

- bindings/ssmt.cpp
- bindings/ssmt.h
- package-lock.json
- tests/js/ssmtTest.js
closes #301 
- Adds heatExchanger binding
> add heatExchanger binding to ssmt

- src/ssmt/FlashTank.cpp
> updated flashtank with new liquid mass flow logic

- CMakeLists.txt
- binding.gyp
- bindings/calculator.cpp
- bindings/calculator.h
- include/calculator/util/CompressedAirReduction.h
- src/calculator/util/CompressedAirReduction.cpp
- tests/CompressedAirReduction.unit.cpp
- tests/js/calculator.js
> Compressed air reduction

- src/ssmt/Boiler.cpp
- src/ssmt/Deaerator.cpp
- src/ssmt/FlashTank.cpp
- src/ssmt/HeatLoss.cpp
- src/ssmt/PRV.cpp
- src/ssmt/Turbine.cpp
- tests/Boiler.unit.cpp
- tests/Deaerator.unit.cpp
- tests/FlashTank.unit.cpp
- tests/HeatLoss.unit.cpp
- tests/PRV.unit.cpp
- tests/Turbine.unit.cpp
- tests/js/ssmtTest.js
* Remove "* 1000" and "/ 1000" from some calculations.
* Update tests.
> Steam calculators: have all energy in kJ #377

- src/calculator/furnace/EfficiencyImprovement.cpp
- tests/EfficiencyImprovement.unit.cpp
- tests/js/furnaceTest.js
connects #3198 from Desktop issues
> Fix parentheses in multiple functions

- include/ssmt/HeatExchanger.h
- tests/HeatExchanger.unit.cpp
- tests/js/ssmtTest.js
Remove "* 1000" and "/ 1000" from calculations.
> HeatExchanger: have all energy in kJ #377

- bindings/fan.h
- bindings/psat.h
- include/calculator/pump/HeadTool.h
- include/calculator/util/Conversion.h
- include/results/InputData.h
- include/results/Results.h
- src/calculator/pump/HeadTool.cpp
- src/calculator/util/Conversion.cpp
- src/results/Results.cpp
- tests/HeadTool.unit.cpp
> Organize psat and fsat bindings for conversion to web assembly bindings

- .travis.yml
- package-lock.json
> Issue 3472

- bindings/phast.h
- include/calculator/losses/GasFlueGasMaterial.h
- src/calculator/losses/GasFlueGasMaterial.cpp
- tests/GasFlueGasMaterial.unit.cpp
- tests/ProcessHeat.unit.cpp
- tests/js/lossesTest.js
- tests/js/processHeat.js
- tests/wasm/wasm-processHeat-test.js
#627   flueGasLossesByVolume binding include all results
> flueGasLossesByVolume binding, include all results
